version: '3.8'

services:
  frontend:
    build:
      context: ./todo-client  # the path to your Vite app
    ports:
      - "3000:80"                         # Expose frontend on port 3000
    restart: always

  backend:
    build:
      context: ./server  # the path to your Express app
    ports:
      - "4001:4001"                        # Expose backend on port 4001
    environment:
      PORT: 4001
      CORS_ORIGIN: '*'
      MONGO_URI: mongodb+srv://shevaitverma:962239@db1.j03ljgt.mongodb.net
      ACCESS_TOKEN_SECRET: bk4wif7hkaew4fghaowb43foai98w4ofiaubew4foia7uw4f
      ACCESS_TOKEN_EXPIRY: 1d
      REFRESH_TOKEN_SECRET: wi74wgafoibfaouwi6b4fop9a7wbpf9a8wb39pf8bawp93f8
      REFRESH_TOKEN_EXPIRY: 10d
    restart: always
