version: '3.8'

services:
  frontend:
    build:
      context: ./todo-client  # the path to your Vite app
    ports:
      - "3000:80"                         # Expose frontend on port 3000
    restart: always

  backend:
    build:
      context: ./server  # the path to your Express app
    ports:
      - "4001:4001"                        # Expose backend on port 4001
    environment:
      PORT: 4001
      CORS_ORIGIN: '*'
      MONGO_URI: url
      ACCESS_TOKEN_SECRET: token
      ACCESS_TOKEN_EXPIRY: 1d
      REFRESH_TOKEN_SECRET: token
      REFRESH_TOKEN_EXPIRY: 10d
    restart: always
