apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shevait/todo-backend
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets