apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "URI"
  ACCESS_TOKEN_SECRET: "f987w4bf0a8w74bf0a8W74BF0A98W74BF9AW7U4BF0A9WU8408F7AW489FYBA0W4F"
  REFRESH_TOKEN_SECRET: "A9WO74VFOA8W974VFOA89W7V4FO98A7VW4-P90F8AHGW8AW673FG8AW7F8WA73FG5ETG"