apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "<your-mongo-uri>"
  ACCESS_TOKEN_SECRET: "<your-access-token>"
  REFRESH_TOKEN_SECRET: "<your-refresh-token>"